services:
  devcontainer:
    build:
      context: ./
      dockerfile: ./.devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - ./:/home/node/src:cached
    command: sleep infinity
